ativosinoa/urls.py
from django.contrib import admin
from django.urls import path, include
import pages.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include("pages.urls", namespace="pages")),
    path('get_stock_data/', pages.views.get_stock_data),
    path('get_stock_options/', pages.views.get_stock_options),
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('success/', views.ContactSuccessView.as_view(), name="success"),
]

pages/models.py
from django.db import models

# Create your models here.
class StockData(models.Model):
    symbol = models.TextField(null=True)
    data = models.TextField(null=True)

pages/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail

class ContactForm(forms.Form):
    email = forms.EmailField()
    ativo = forms.CharField(max_length=15)
    condition = forms.ChoiceField(choices=[('passar de', 'passar de'), ('cair de', 'cair de')])
    price = forms.CharField(max_length=70)

    def get_info(self):
        """
        Method that returns formatted information
        :return: subject, msg
        """
        # Cleaned data
        cl_data = super().clean()

        from_email = cl_data.get('email')
        ativo = cl_data.get('ativo')
        condition = cl_data.get('condition')
        price = cl_data.get('price')

        if(condition == "passar de"):
            msg = f'\nO valor do ativo {ativo} está mais caro que {price}$, é melhor vender!'
        else:
            msg = f'\nO valor do ativo {ativo} está mais barato que {price}$, é hora de comprar!'

        return ativo, msg, from_email

    def send(self):
        
        subject, msg, email = self.get_info()

        send_mail(
            subject=f'Ativo - {subject}',
            message=msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[email]
        )

pages/views.py
from django.shortcuts import render
from django.views.generic import FormView, TemplateView
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import StockData
from django.contrib import messages
from .forms import ContactForm
from django.urls import reverse_lazy

import requests
import json


APIKEY = '8FV7ILHNL2UNT059' 

DATABASE_ACCESS = True 
#if False, the app will always query the Alpha Vantage APIs regardless of whether the stock data for a given ticker is already in the local database

class HomePageView(TemplateView):
    template_name = "home.html"

@csrf_exempt
def get_stock_data(request):
    #get ticker from the AJAX POST request
    ticker = request.POST.get('ticker', 'null')
    ticker = ticker.upper()

    if DATABASE_ACCESS == True:
        #checking if the database already has data stored for this ticker before querying the Alpha Vantage API
        if StockData.objects.filter(symbol=ticker).exists(): 
            #We have the data in our database! Get the data from the database directly and send it back to the frontend AJAX call
            entry = StockData.objects.filter(symbol=ticker)[0]
            return HttpResponse(entry.data, content_type='application/json')

    #obtain stock data from Alpha Vantage APIs
    #get adjusted close data
    price_series = requests.get(f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol={ticker}&apikey={APIKEY}&outputsize=full').json()
    
    #get SMA (simple moving average) data
    sma_series = requests.get(f'https://www.alphavantage.co/query?function=SMA&symbol={ticker}&interval=daily&time_period=10&series_type=close&apikey={APIKEY}').json()

    #package up the data in an output dictionary 
    output_dictionary = {}
    output_dictionary['prices'] = price_series
    output_dictionary['sma'] = sma_series

    #save the dictionary to database
    temp = StockData(symbol=ticker, data=json.dumps(output_dictionary))
    temp.save()

    if(output_dictionary['prices']):
        messages.error(request, 'Não existem ativos com essa sigla')

    

    #return the data back to the frontend AJAX call 
    return HttpResponse(json.dumps(output_dictionary), content_type='application/json')

@csrf_exempt
def get_stock_options(request):
    ticker = request.POST.get('ticker', 'null')
    ticker = ticker.upper()
    candidates = requests.get(f'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords={ticker}&apikey={APIKEY}').json()
    cand_list = []
    if 'Note' not in candidates:
        for i in candidates['bestMatches']:
            cand_list.append(i['1. symbol'])
    return JsonResponse(candidates, safe=False)

class ContactView(FormView):
    template_name = 'pages/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('pages:success')

    def form_valid(self, form):
        # Calls the custom send method
        form.send()
        return super().form_valid(form)

class ContactSuccessView(TemplateView):
    template_name = 'pages/success.html'

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous" />
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Ativos Inoa</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <div id = "content">
        {% include "account/messages.html" %}
    </div>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
<script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 3000)
  </script> 
</html>

templates/baseEmail.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Email Send</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous" />
  </head>
  
  <body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Ativos Inoa</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    {% block body %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous">
    </script>
  </body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Ativos Inoa{% endblock %}

{% block content %}
    <!DOCTYPE html>
    <html>
    <head>
        <!--<link rel="stylesheet" href="style.css">-->
        <script src="https://cdn.jsdelivr.net/npm/chart.js@3.2.1/dist/chart.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <title>Stock Visualizer</title>
    </head>

    <body>
    <h2>Verifique os gráficos de ativos!</h2>
    <br>

    <div class='col-sm-12 col-lg-12 col-md-12'>
    
        <form class="form-inline">
          <label class="sr-only" for="ticker-input">Sigla</label>
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Sigla</div>
            </div>
            <input type="text" class="form-control" id="ticker-input" placeholder="AAPL">
          </div>
  
  
  
          <label class="sr-only" for="period">Username</label>
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Período (dias)</div>
            </div>
            <input type="number" class="form-control" id="period" placeholder="7">
          </div>
  
          <input type="button"  class="btn btn-primary mb-2" value="Pesquisar" id="submit-btn">
        </form>
    </div>

    <div id="graph-area" style="height:80%; width:80%;">
    <canvas id="myChart"></canvas>
    </div>

    <br>
    {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'pages:contact' %}"><button  class="btn btn-primary mb-2" id="submit-btn">Notificar-me por e-mail</button></a>
    {% else %}
    <h4>(Para receber notificações por e-mail, realize o login)</h4>
    <br>
    {% endif %}

    <div id="graph-area" style="height:80%; width:80%;">
    <canvas id="myChart"></canvas>
    </div>

    <!-- Abaixo pode-se encontrar o script que sugeria ao usuário os ativos presentes na base de dados da API.
    Como essa funcionalidade gastava muitos usos da API, resolvi retirar. -->

    <!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
    
    <!-- <script>
        $('#ticker-input').keyup(function () {
            if($('#ticker-input').val() != ""){
                var tickerText = $('#ticker-input').val();
                $.ajax({
                    type: "POST",
                    url: "/get_stock_options/",
                    data: {
                        'ticker': tickerText,
                    },
                    success: function (res, status) {  
                        console.log(res)                  
                        $("#ticker-input").autocomplete({
                            source: res,
                            minLength: 1
                        });
                    }
                });
            }
        });
    </script> -->

    <script>
        $(document).ready(function(){
            // Right after the page is loaded, we get the stock data (default to AAPL) from the Django backend (the 'get_stock_data' function) for plotting
            $.ajax({
                type: "POST",
                url: "/get_stock_data/",
                data: {
                    'ticker': 'AAPL',
                },
                success: function (res, status) {
                    // AAPL's stock price and SMA data is now in the "res" object
                    var tickerDisplay = res['prices']['Meta Data']['2. Symbol'];
                    var graphTitle = tickerDisplay + ' (dados dos últimos 365 dias)'

                    var priceSeries = res['prices']['Time Series (Daily)'];
                    var daily_adjusted_close = [];
                    var dates = [];

                    price_data_parse = function(){
                        for (let key in priceSeries) {
                            daily_adjusted_close.push(Number(priceSeries[key]['5. adjusted close']));
                            dates.push(String(key));
                        }

                    };
                    price_data_parse();

                    var smaSeries = res['sma']['Technical Analysis: SMA'];
                    var sma_data = [];

                    sma_data_parse = function(){
                        for (let key in smaSeries) {
                            sma_data.push(Number(smaSeries[key]['SMA']));
                        }

                    };
                    sma_data_parse();

                    // only keep the latest 365 data points (i.e., data for the latest 365 trading days) for the three lists below
                    daily_adjusted_close.reverse().slice(365);
                    sma_data.reverse().slice(365);
                    dates.reverse().slice(365);

                    //instruct Chart.js to plot the graph, with "dates" as the x-axis labels and "daily_adjusted_close" and "sma_data" as the y-axis values
                    var ctx = document.getElementById('myChart').getContext('2d');
                    var myChart = new Chart(ctx, {
                    animationEnabled: true,
	                zoomEnabled: true,
                    type: 'line',
                        data: {
                            labels: dates.slice(-365),
                            datasets: [
                                {
                                    label: 'Fechamento Diário Ajustado (DAC)',
                                    data: daily_adjusted_close.slice(-365),
                                    backgroundColor: [
                                        'green',
                                    ],
                                    borderColor: [
                                        'green',
                                    ],
                                    borderWidth: 1
                                },
                                {
                                    label: 'Média Móvel Simples (SMA)',
                                    data: sma_data.slice(-365),
                                    backgroundColor: [
                                        'blue',
                                    ],
                                    borderColor: [
                                        'blue',
                                    ],
                                    borderWidth: 1
                                },
                            ]
                        },
                        options: {
                            responsive: true,
                            scales: {
                                y: {
                                    //beginAtZero: false
                                }
                            },
                            plugins: {
                                legend: {
                                position: 'top',
                                },
                                title: {
                                display: true,
                                text: graphTitle
                                }
                            }
                        }
                    });

                }
            });
        });

        $('#submit-btn').click(function() {
            // when the user specifies a new ticker, we call the Django backend (the 'get_stock_data' function) to get the stock data and refresh the graph. 
            // obtain the ticker string from the input textbox
            var tickerText = $('#ticker-input').val();
            var period = $('#period').val();
            $.ajax({
                type: "POST",
                url: "/get_stock_data/",
                data: {
                    'ticker': tickerText,
                },
                success: function (res, status) {
                    // stock price and SMA data for the user-specified ticker is now in the "res" object
                    if(res['prices']['Error Message']){
                        location.reload()
                    }
                    else{
                        if(res['prices']['Note'] || !res['prices']['Meta Data']){
                            location.reload()
                        }
                        var tickerDisplay = res['prices']['Meta Data']['2. Symbol'];
                        var graphTitle = tickerDisplay + ' (dados dos últimos '+ period + ' dias)';
                    }

                    var priceSeries = res['prices']['Time Series (Daily)'];
                    var daily_adjusted_close = [];
                    var dates = [];

                    price_data_parse = function(){
                        for (let key in priceSeries) {
                            daily_adjusted_close.push(Number(priceSeries[key]['5. adjusted close']));
                            dates.push(String(key));
                        }

                    };
                    price_data_parse();

                    var smaSeries = res['sma']['Technical Analysis: SMA'];
                    var sma_data = [];

                    sma_data_parse = function(){
                        for (let key in smaSeries) {
                            sma_data.push(Number(smaSeries[key]['SMA']));
                        }

                    };
                    sma_data_parse();


                    // only keep the latest x data points (i.e., data for the latest x trading days) for the three lists below

                    daily_adjusted_close.reverse().slice(period);
                    sma_data.reverse().slice(period);
                    dates.reverse().slice(period);

                    //instruct Chart.js to plot the graph, with "dates" as the x-axis labels and "daily_adjusted_close" and "sma_data" as the y-axis values
                    $('#myChart').remove(); // this is my <canvas> element
                    $('#graph-area').append('<canvas id="myChart"><canvas>');
                    var ctx = document.getElementById('myChart').getContext('2d');
                    var myChart = new Chart(ctx, {
                    type: 'line',
                    zoomEnabled: true,
                        data: {
                            labels: dates.slice(-period),
                            datasets: [
                                {
                                    label: 'Fechamento Diário Ajustado (DAC)',
                                    data: daily_adjusted_close.slice(-period),
                                    backgroundColor: [
                                        'green',
                                    ],
                                    borderColor: [
                                        'green',
                                    ],
                                    borderWidth: 1
                                },
                                {
                                    label: 'Média Móvel Simples (SMA)',
                                    data: sma_data.slice(-period),
                                    backgroundColor: [
                                        'blue',
                                    ],
                                    borderColor: [
                                        'blue',
                                    ],
                                    borderWidth: 1
                                },
                            ]
                        },
                        options: {
                            responsive: true,
                            scales: {
                                y: {
                                    //beginAtZero: false
                                }
                            },
                            plugins: {
                                legend: {
                                position: 'top',
                                },
                                title: {
                                display: true,
                                text: graphTitle
                                }
                            }
                        }
                    });

                }
            });


        });

    </script>

    </body>
    </html>
{% endblock %}

templates/pages/contact.html
{% extends 'baseEmail.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto my-4 text-center">
    <h1>Receber notificação por e-mail</h1>
</div>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
    <button class="btn btn-success my-3" type="submit">Notificar-me</button>
    </form>
</div>
{% endblock %}

templates/pages/success.html
{% extends 'baseEmail.html' %}

{% block body %}
<div class="mx-auto my-4 text-center">
    <h2 class="fw-bolder text-success">Enviaremos o e-mail assim que as condições forem cumpridas</h2>
    <p class="my-5"><a href="{% url 'pages:home' %}">Inoa Ativos</a></p>
</div>
{% endblock %}